#!/bin/bash - 
#===============================================================================
#
#          FILE: getlinks.sh
#
#          TODO: add differentiation of soft- & hard-links
#===============================================================================

CYAN='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m'

default_dir="$(pwd)"
search_dir=${1:-$default_dir}
list=()
linkAmount=0

function gatherLinkList(){
	while read line
	do
		list+=("$line")
	done< <(ls -l "$search_dir" | grep -P '^l' | sed 's~[a-z ]\+[0-9][a-zA-Z ]\+.\+ [0-9][0-9]:\?[0-9][0-9] ~~' | sed 's~->~→~g;s~^ *~~;s~^~ ~')

	linkAmount=${#list[@]}
}

function printLinkList(){
	i=0
	until [[ "$i" == "$linkAmount" ]];do
		echo "${list[$i]}"
		i=$((i+1))
	done
}



if [[ "$search_dir" != '/'* ]]
then
	search_dir="${PWD}/$search_dir"
fi

gatherLinkList

printf "${CYAN}${linkAmount} soft-links in directory: ${WHITE}\'$search_dir\'${NC}\n${WHITE}---\n${NC}"

printLinkList

printf "${WHITE}---\n${NC}"
